version: '3.8'

services:
  evaluator_service:
    build: ./Evaluator-Service
    container_name: evaluator_service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - submission_service
      - redis
    networks:
      - leetcode_network

  problem_service:
    build: ./Problem-Service
    container_name: problem_service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - ATLAS_DB_URL=mongodb+srv://problem-service:kishan@cluster-problem-service.vypzmrx.mongodb.net/?appName=Cluster-Problem-Service
      - LOG_DB_URL=mongodb+srv://problem-service:kishan@cluster-problem-service.vypzmrx.mongodb.net/?appName=Cluster-Problem-Service
    networks:
      - leetcode_network

  submission_service:
    build: ./Submission-Service
    container_name: submission_service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - ATLAS_DB_URL=mongodb+srv://problem-service:kishan@cluster-problem-service.vypzmrx.mongodb.net/?appName=Cluster-Problem-Service
      - NODE_ENV=development
      - PROBLEM_API_TIMEOUT=5000
      - WEBHOOK_TIMEOUT=5000
      - SUBMISSION_TIMEOUT=3000
      - QUEUE_NAME=SubmissionQueue
      - JOB_NAME=SubmissionJob
      - SUBMISSION_SERVICE_WEBHOOK_URL=http://submission_service:5000/api/v1/submissions
      - EVALUATOR_SERVICE_URL=http://evaluator_service:4000
      - PROBLEM_ADMIN_SERVICE_URL=http://problem_service:3000
      - REDIS_DB=0
    depends_on:
      - redis
      - problem_service
    networks:
      - leetcode_network

  user_service:
    build: ./User-Service
    container_name: user_service
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
      - NODE_ENV=development
      - ATLAS_DB_URL=mongodb+srv://problem-service:kishan@cluster-problem-service.vypzmrx.mongodb.net/?appName=Cluster-Problem-Service
      - JWT_SECRET=Sunshine
      - JWT_EXPIRES_IN=24h
      - JWT_REFRESH_SECRET=Blue
      - JWT_REFRESH_EXPIRES_IN=7d
    networks:
      - leetcode_network

  redis:
    image: redis:alpine
    container_name: leetcode_redis
    ports:
      - "6379:6379"
    networks:
      - leetcode_network

networks:
  leetcode_network:
    driver: bridge
